# Generated by Django 5.0.6 on 2024-06-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='situation',
            field=models.BooleanField(default=True),
        ),
    ]
