# Generated by Django 5.0.6 on 2024-06-28 07:59

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DumpTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='کد دستگاه')),
                ('model', models.CharField(max_length=30, verbose_name='مدل')),
            ],
            options={
                'verbose_name': 'دامپ تراک',
                'verbose_name_plural': 'دامپ تراک\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_code', models.CharField(max_length=10, unique=True, verbose_name='کد پرسنلی')),
                ('first_name', models.CharField(max_length=30, verbose_name='نام')),
                ('last_name', models.CharField(max_length=30, verbose_name='نام خانوادگی')),
            ],
            options={
                'verbose_name': 'اپراتور',
                'verbose_name_plural': 'اپراتورها',
            },
        ),
        migrations.CreateModel(
            name='Downtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع')),
                ('start_time', models.TimeField(verbose_name='زمان شروع')),
                ('end_date', django_jalali.db.models.jDateField(verbose_name='تاریخ پایان')),
                ('end_time', models.TimeField(verbose_name='زمان پایان')),
                ('reason', models.TextField(verbose_name='علت خرابی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('dump_truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dumptrucks.dumptruck', verbose_name='دامپ تراک')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dumptrucks.operator', verbose_name='اپراتور')),
            ],
            options={
                'verbose_name': 'خرابی',
                'verbose_name_plural': 'خرابی\u200cها',
            },
        ),
    ]
