# Generated by Django 5.0.6 on 2024-06-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dumptrucks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='group',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], default='a', max_length=1, verbose_name='گروه'),
            preserve_default=False,
        ),
    ]
