# Generated by Django 5.0.6 on 2024-06-30 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dumptrucks', '0002_operator_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='dumptruck',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='dumptruck',
            name='type',
            field=models.CharField(choices=[('shovel', 'شاول'), ('dump_truck', 'دامپتراک'), ('excavator', 'بیل مکانیکی'), ('drilling_machine', 'دستگاه حفاری')], default='دامپتراک', max_length=20, verbose_name='نوع دستگاه'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='downtime',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dumptrucks.failurereason', verbose_name='علت خرابی'),
        ),
    ]
