# Generated by Django 5.0.6 on 2024-07-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dumptrucks', '0003_failurereason_dumptruck_is_active_dumptruck_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس'),
        ),
        migrations.AddField(
            model_name='operator',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='سمت'),
        ),
    ]
